[package]
name = "rust_toolkit_web"
version = "0.1.0"
edition = "2024"

[dependencies]
warp = "0.3"
tokio = { version = "1", features = ["full"] }
serde = { version = "1.0", features = ["derive"] }       # For JSON
serde_json = "1.0"